---
repo:
- '*'

config/github:
- ['.github/*', '.github/**/*']

dependencies:
- build.sbt
- pom.xml
- requirements.txt
- package.json
- yarn.lock
- package-lock.json

docker:
- Dockerfile

documentation:
- '*.md'
- '*.mdx'
- docs/*
- docs/**/*

frontend:
- src/*
- src/**/*

blog:
- blog/*
- blog/**/*

javascript:
- '*.js'
- '**/*.js'
- package.json
- yarn.lock
- package-lock.json

licenses:
- LICENSES/*
- LICENSES/**/*

python:
- requirements.txt
- app/**/*.py
- '**/*.py'

scala:
- build.sbt
- pom.xml
- src/**/*.scala
